name: Github CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Build Project'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm i
      - run: npm run build

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: Knst.su
          path: .output/
  build-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Knst.su
          path: .output/

      - name: Extract version
        id: get_version
        run: echo ::set-output name=version::$(node -p "require('./package.json').version")

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/iskonstantin/knst.su:${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}